/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CRUDC;

/**
 *
 * @author hecto
 */
public class AltasCarrera extends javax.swing.JFrame {

    private java.util.ArrayList<Clases.Carrera> carr;
    private ReportesCarrera reportes;

    /**
     * Creates new form AltasCarrera
     */
    public AltasCarrera() {
        carr = new java.util.ArrayList();
        initComponents();
        
        reportes = new ReportesCarrera();
        reportes.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUniversidad = new javax.swing.JTextField();
        txtSemestres = new javax.swing.JTextField();
        lblId = new javax.swing.JLabel();
        Guardar = new javax.swing.JButton();
        lblNombre = new javax.swing.JLabel();
        Mostrar = new javax.swing.JButton();
        lblPlantel = new javax.swing.JLabel();
        Regresar = new javax.swing.JButton();
        lblDuracion = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblUniversidad = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblSemestres = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtPlantel = new javax.swing.JTextField();
        txtDuracion = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblId.setText("ID:");

        Guardar.setText("Guardar");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });

        lblNombre.setText("Nombre: ");

        Mostrar.setText("Mostrar");
        Mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarActionPerformed(evt);
            }
        });

        lblPlantel.setText("Plantel:");

        Regresar.setText("Regresar");
        Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarActionPerformed(evt);
            }
        });

        lblDuracion.setText("Duracion:");

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel7.setText("ALTAS - CARRERA");

        lblUniversidad.setText("Universidad:");

        lblSemestres.setText("Semestres:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblId)
                                    .addComponent(lblNombre))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPlantel)
                                    .addComponent(lblDuracion)
                                    .addComponent(lblUniversidad)
                                    .addComponent(lblSemestres))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPlantel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtUniversidad, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSemestres, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(Guardar)
                        .addGap(51, 51, 51)
                        .addComponent(Mostrar)
                        .addGap(49, 49, 49)
                        .addComponent(Regresar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblId)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPlantel)
                    .addComponent(txtPlantel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDuracion)
                    .addComponent(txtDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUniversidad)
                    .addComponent(txtUniversidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSemestres)
                    .addComponent(txtSemestres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Guardar)
                    .addComponent(Mostrar)
                    .addComponent(Regresar))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        boolean datosIngresados = !txtId.getText().isEmpty() || !txtNombre.getText().isEmpty() || !txtPlantel.getText().isEmpty() || !txtDuracion.getText().isEmpty() || !txtUniversidad.getText().isEmpty() || !txtSemestres.getText().isEmpty();

        if (!datosIngresados) {
            javax.swing.JOptionPane.showMessageDialog(this, "No se han ingresado datos para guardar.", "Advertencia", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (txtId.getText().isEmpty() || txtNombre.getText().isEmpty() || txtPlantel.getText().isEmpty() || txtDuracion.getText().isEmpty() || txtUniversidad.getText().isEmpty() || txtSemestres.getText().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Todos los campos deben ser llenados.", "Advertencia", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        int id = Integer.parseInt(txtId.getText());
        String nom = txtNombre.getText();
        String pla = txtPlantel.getText();
        byte dur = Byte.parseByte(txtDuracion.getText());
        String uni = txtUniversidad.getText();
        byte sems = Byte.parseByte(txtSemestres.getText());
        Clases.Carrera car = new Clases.Carrera(id, nom, pla, dur, uni, sems);

        try {
            java.io.FileInputStream fis = new java.io.FileInputStream("Carreras");
            java.io.ObjectInputStream ois = new java.io.ObjectInputStream(fis);
            carr = (java.util.ArrayList<Clases.Carrera>) ois.readObject();
            ois.close();
        } catch (java.io.IOException | ClassNotFoundException ex) {
            //Si no hay datos existentes, no hacer nada
        }

        carr.add(car);

        try {
            java.io.FileOutputStream fos = new java.io.FileOutputStream("Carreras");
            java.io.ObjectOutputStream oos = new java.io.ObjectOutputStream(fos);
            oos.writeObject(carr);
            oos.close();

            txtId.setText("");
            txtNombre.setText("");
            txtPlantel.setText("");
            txtDuracion.setText("");
            txtUniversidad.setText("");
            txtSemestres.setText("");

        } catch (java.io.IOException es) {
            System.out.println("Error al Guardar en el archivo " + es.toString());
        }
    }//GEN-LAST:event_GuardarActionPerformed

    private void MostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarActionPerformed
        try {
            java.io.FileInputStream fis = new java.io.FileInputStream("Carreras");
            java.io.ObjectInputStream ois = new java.io.ObjectInputStream(fis);
            carr = (java.util.ArrayList) ois.readObject();
            ois.close();
        } catch (java.io.IOException | ClassNotFoundException es) {
            System.out.println("Error al Guardar en el archivo " + es.toString());
        }
        for (Clases.Carrera a : carr) {
            System.out.println(a);
        }

        this.dispose();

        reportes.setVisible(true);
    }//GEN-LAST:event_MostrarActionPerformed

    private void RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarActionPerformed
        this.dispose();

        Menus.MenuCarrera menuPrincipal = new Menus.MenuCarrera();
        menuPrincipal.setVisible(true);
    }//GEN-LAST:event_RegresarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Guardar;
    private javax.swing.JButton Mostrar;
    private javax.swing.JButton Regresar;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblDuracion;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPlantel;
    private javax.swing.JLabel lblSemestres;
    private javax.swing.JLabel lblUniversidad;
    private javax.swing.JTextField txtDuracion;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPlantel;
    private javax.swing.JTextField txtSemestres;
    private javax.swing.JTextField txtUniversidad;
    // End of variables declaration//GEN-END:variables
}
