/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CRUDC;

/**
 *
 * @author hecto
 */
public class BajasCarrera extends javax.swing.JFrame {

    private java.util.ArrayList<Clases.Carrera> carr;

    private int indiceActual = 0;

    /**
     * Creates new form BajasCarrera
     */
    public BajasCarrera() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblElegir = new javax.swing.JLabel();
        txtElegir = new javax.swing.JTextField();
        Buscar = new javax.swing.JButton();
        Borrar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        Regresar = new javax.swing.JButton();
        lblId = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblPlantel = new javax.swing.JLabel();
        lblDuracion = new javax.swing.JLabel();
        lblUniversidad = new javax.swing.JLabel();
        lblSemestres = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblElegir.setText("Número de ID:");

        Buscar.setText("Buscar");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });

        Borrar.setText("Dar de baja");
        Borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrarActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel7.setText("BAJAS - CARRERAS");

        Regresar.setText("REGRESAR");
        Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarActionPerformed(evt);
            }
        });

        lblId.setText("ID:");

        lblNombre.setText("Nombre: ");

        lblPlantel.setText("Plantel:");

        lblDuracion.setText("Duracion:");

        lblUniversidad.setText("Universidad:");

        lblSemestres.setText("Semestres:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblId)
                        .addComponent(lblPlantel)
                        .addComponent(lblDuracion)
                        .addComponent(lblUniversidad)
                        .addComponent(lblSemestres)
                        .addComponent(lblNombre))
                    .addComponent(lblElegir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtElegir, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(Buscar)
                .addGap(26, 26, 26))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(Borrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Regresar))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(103, 103, 103))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtElegir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblElegir)
                    .addComponent(Buscar))
                .addGap(26, 26, 26)
                .addComponent(lblId)
                .addGap(9, 9, 9)
                .addComponent(lblNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPlantel)
                .addGap(9, 9, 9)
                .addComponent(lblDuracion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblUniversidad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSemestres)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Borrar)
                    .addComponent(Regresar))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        String idText = txtElegir.getText();
        txtElegir.setText("");

        try {
            int id = Integer.parseInt(idText);
            boolean encontrado = false;
            for (int i = 0; i < carr.size(); i++) {
                if (carr.get(i).getId() == id) {
                    mostrarDatos(i);
                    encontrado = true;
                    break;
                }
            }
            if (!encontrado) {
                javax.swing.JOptionPane.showMessageDialog(this, "ID no encontrada.");
            }
        } catch (NumberFormatException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor ingrese un numero valido en el ID.");
        }
    }//GEN-LAST:event_BuscarActionPerformed

    private void BorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrarActionPerformed
        String idText = txtElegir.getText();

        try {
            int id = Integer.parseInt(idText);
            boolean encontrado = false;
            for (int i = 0; i < carr.size(); i++) {
                if (carr.get(i).getId() == id) {
                    carr.remove(i);
                    encontrado = true;
                    break;
                }
            }
            if (encontrado) {
                javax.swing.JOptionPane.showMessageDialog(this, "Carrera borrada exitosamente.");

                try {
                    java.io.FileOutputStream fos = new java.io.FileOutputStream("Carreras");
                    java.io.ObjectOutputStream oos = new java.io.ObjectOutputStream(fos);
                    oos.writeObject(carr);
                    oos.close();
                } catch (java.io.IOException ex) {
                    System.out.println("Error al guardar datos en el archivo: " + ex.toString());
                }

                lblId.setText("ID");
                lblNombre.setText("Nombre");
                lblPlantel.setText("Plantel");
                lblDuracion.setText("Duracion");
                lblUniversidad.setText("Universidad");
                lblSemestres.setText("Semestres");
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "ID no encontrada.");
            }
        } catch (NumberFormatException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor ingrese un numero valido en el ID.");
        }
    }//GEN-LAST:event_BorrarActionPerformed

    private void RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarActionPerformed
        this.dispose();

        Menus.MenuCarrera menuPrincipal = new Menus.MenuCarrera();
        menuPrincipal.setVisible(true);
    }//GEN-LAST:event_RegresarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Borrar;
    private javax.swing.JButton Buscar;
    private javax.swing.JButton Regresar;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblDuracion;
    private javax.swing.JLabel lblElegir;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPlantel;
    private javax.swing.JLabel lblSemestres;
    private javax.swing.JLabel lblUniversidad;
    private javax.swing.JTextField txtElegir;
    // End of variables declaration//GEN-END:variables

    private void mostrarDatos(int index) {
        if (index >= 0 && index < carr.size()) {
            Clases.Carrera carrera = carr.get(index);
            lblId.setText("Matricula: " + carrera.getId());
            lblNombre.setText("Nombre: " + carrera.getNombre());
            lblPlantel.setText("Apellidos: " + carrera.getPlantel());
            lblDuracion.setText("Edad: " + carrera.getDuracion());
            lblUniversidad.setText("Carrera: " + carrera.getUniversidad());
            lblSemestres.setText("Semestre: " + carrera.getSemestres());
        }
    }

}
