/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CRUDC;

/**
 *
 * @author hecto
 */
public class ModificarCarrera extends javax.swing.JFrame {

    private java.util.ArrayList<Clases.Carrera> carr;

    private int indiceActual = 0;

    /**
     * Creates new form ModificarCarrera
     */
    public ModificarCarrera() {
        initComponents();

        try {
            java.io.FileInputStream fis = new java.io.FileInputStream("Carreras");
            java.io.ObjectInputStream ois = new java.io.ObjectInputStream(fis);
            carr = (java.util.ArrayList<Clases.Carrera>) ois.readObject();
            ois.close();
            mostrarDatos(indiceActual);
        } catch (java.io.IOException | ClassNotFoundException es) {
            System.out.println("Error al cargar datos desde el archivo: " + es.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDuracion = new javax.swing.JLabel();
        lblUniversidad = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblElegir = new javax.swing.JLabel();
        lblSemestres = new javax.swing.JLabel();
        txtElegir = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        Buscar = new javax.swing.JButton();
        txtPlantel = new javax.swing.JTextField();
        txtUniversidad = new javax.swing.JTextField();
        txtDuracion = new javax.swing.JTextField();
        txtSemestres = new javax.swing.JTextField();
        Modificar = new javax.swing.JButton();
        lblId = new javax.swing.JLabel();
        Regresar1 = new javax.swing.JButton();
        lblNombre = new javax.swing.JLabel();
        lblPlantel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblDuracion.setText("Duracion:");

        lblUniversidad.setText("Universidad:");

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel7.setText("MODIFICAR - CARRERA");

        lblElegir.setText("ID a modificar:");

        lblSemestres.setText("Semestres:");

        Buscar.setText("Buscar");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });

        Modificar.setText("Modificar");
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });

        lblId.setText("ID:");

        Regresar1.setText("REGRESAR");
        Regresar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Regresar1ActionPerformed(evt);
            }
        });

        lblNombre.setText("Nombre: ");

        lblPlantel.setText("Plantel:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblElegir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtElegir, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addComponent(Buscar)
                .addGap(26, 26, 26))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblId)
                                    .addComponent(lblNombre))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(Modificar)
                                    .addGap(82, 82, 82)
                                    .addComponent(Regresar1))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblPlantel)
                                        .addComponent(lblDuracion)
                                        .addComponent(lblUniversidad)
                                        .addComponent(lblSemestres))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtPlantel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtUniversidad, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtSemestres, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(99, 99, 99))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(89, 89, 89))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtElegir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblElegir)
                    .addComponent(Buscar))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblId)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPlantel)
                    .addComponent(txtPlantel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDuracion)
                    .addComponent(txtDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUniversidad)
                    .addComponent(txtUniversidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSemestres)
                    .addComponent(txtSemestres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Modificar)
                    .addComponent(Regresar1))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        String idBuscar = txtElegir.getText().trim();

        if (idBuscar.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor ingrese una ID a buscar.");
        } else {
            boolean encontrado = false;
            int indiceCarrera = -1;
            for (int i = 0; i < carr.size(); i++) {
                if (String.valueOf(carr.get(i).getId()).equals(idBuscar)) {
                    encontrado = true;
                    indiceCarrera = i;
                    break;
                }
            }

            if (encontrado) {
                mostrarDatos(indiceCarrera);
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "La ID especificada no existe en la base de datos.");
            }

            txtElegir.setText("");
        }
    }//GEN-LAST:event_BuscarActionPerformed

    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed
        String idModificar = txtId.getText().trim();
        String nuevoNombre = txtNombre.getText().trim();
        String nuevoPlantel = txtPlantel.getText().trim();
        String nuevaDuracion = txtDuracion.getText().trim();
        String nuevaUniversidad = txtUniversidad.getText().trim();
        String nuevosSemestres = txtSemestres.getText().trim();

        Clases.Carrera carreraModificar = null;
        for (Clases.Carrera carrera : carr) {
            if (String.valueOf(carrera.getId()).equals(idModificar)) {
                carreraModificar = carrera;
                break;
            }
        }

        if (!nuevoNombre.isEmpty()) {
            carreraModificar.setNombre(nuevoNombre);
        }
        if (!nuevoPlantel.isEmpty()) {
            carreraModificar.setPlantel(nuevoPlantel);
        }
        if (!nuevaDuracion.isEmpty()) {
            int nuevaDur = Integer.parseInt(nuevaDuracion);
            carreraModificar.setDuracion((byte) nuevaDur);
        }
        if (!nuevaUniversidad.isEmpty()) {
            carreraModificar.setUniversidad(nuevaUniversidad);
        }
        if (!nuevosSemestres.isEmpty()) {
            int nuevoSemestre = Integer.parseInt(nuevosSemestres);
            carreraModificar.setSemestres((byte) nuevoSemestre);
        }

        txtId.setText("");
        txtNombre.setText("");
        txtPlantel.setText("");
        txtDuracion.setText("");
        txtUniversidad.setText("");
        txtSemestres.setText("");

        try {
            java.io.FileOutputStream fos = new java.io.FileOutputStream("Carreras");
            java.io.ObjectOutputStream oos = new java.io.ObjectOutputStream(fos);
            oos.writeObject(carr);
            oos.close();
            javax.swing.JOptionPane.showMessageDialog(this, "Los datos se han modificado y guardado correctamente.");
        } catch (java.io.IOException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al guardar los datos modificados: " + ex.toString());
        }

    }//GEN-LAST:event_ModificarActionPerformed

    private void Regresar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Regresar1ActionPerformed
        this.dispose();

        Menus.MenuCarrera menuPrincipal = new Menus.MenuCarrera();
        menuPrincipal.setVisible(true);
    }//GEN-LAST:event_Regresar1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buscar;
    private javax.swing.JButton Modificar;
    private javax.swing.JButton Regresar1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblDuracion;
    private javax.swing.JLabel lblElegir;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPlantel;
    private javax.swing.JLabel lblSemestres;
    private javax.swing.JLabel lblUniversidad;
    private javax.swing.JTextField txtDuracion;
    private javax.swing.JTextField txtElegir;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPlantel;
    private javax.swing.JTextField txtSemestres;
    private javax.swing.JTextField txtUniversidad;
    // End of variables declaration//GEN-END:variables

    private void mostrarDatos(int index) {
        if (index >= 0 && index < carr.size()) {
            Clases.Carrera carrera = carr.get(index);
            lblId.setText("Matricula: " + carrera.getId());
            lblNombre.setText("Nombre: " + carrera.getNombre());
            lblPlantel.setText("Apellidos: " + carrera.getPlantel());
            lblDuracion.setText("Edad: " + carrera.getDuracion());
            lblUniversidad.setText("Carrera: " + carrera.getUniversidad());
            lblSemestres.setText("Semestre: " + carrera.getSemestres());
        }
    }

}
