/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CRUDC;

/**
 *
 * @author hecto
 */
public class ReportesCarrera extends javax.swing.JFrame {

    private java.util.ArrayList<Clases.Carrera> carr;

    private int indiceActual = 0;

    /**
     * Creates new form ReportesCarrera
     */
    public ReportesCarrera() {
        initComponents();

        try {
            java.io.FileInputStream fis = new java.io.FileInputStream("Carreras");
            java.io.ObjectInputStream ois = new java.io.ObjectInputStream(fis);
            carr = (java.util.ArrayList<Clases.Carrera>) ois.readObject();
            ois.close();
            mostrarDatos(indiceActual);
        } catch (java.io.IOException | ClassNotFoundException es) {
            System.out.println("Error al cargar datos desde el archivo: " + es.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Principio = new javax.swing.JButton();
        Regresar = new javax.swing.JButton();
        Modificar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        Siguiente = new javax.swing.JButton();
        Anterior = new javax.swing.JButton();
        Ultimo = new javax.swing.JButton();
        lblPlantel = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        lblSemestres = new javax.swing.JLabel();
        lblUniversidad = new javax.swing.JLabel();
        lblDuracion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Principio.setText("Principio");
        Principio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrincipioActionPerformed(evt);
            }
        });

        Regresar.setText("REGRESAR");
        Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarActionPerformed(evt);
            }
        });

        Modificar.setText("MODIFICAR");
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel7.setText("REPORTES - CARRERA");

        Siguiente.setText("Siguiente");
        Siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SiguienteActionPerformed(evt);
            }
        });

        Anterior.setText("Anterior");
        Anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnteriorActionPerformed(evt);
            }
        });

        Ultimo.setText("Ultimo");
        Ultimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UltimoActionPerformed(evt);
            }
        });

        lblPlantel.setText("Plantel:");

        lblNombre.setText("Nombre: ");

        lblId.setText("ID:");

        lblSemestres.setText("Semestres:");

        lblUniversidad.setText("Universidad:");

        lblDuracion.setText("Duracion:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(Modificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Regresar)
                .addGap(67, 67, 67))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(Anterior)
                        .addGap(18, 18, 18)
                        .addComponent(Siguiente)
                        .addGap(18, 18, 18)
                        .addComponent(Ultimo)
                        .addGap(18, 18, 18)
                        .addComponent(Principio))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblId)
                            .addComponent(lblNombre)
                            .addComponent(lblPlantel)
                            .addComponent(lblDuracion)
                            .addComponent(lblUniversidad)
                            .addComponent(lblSemestres))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(lblId)
                .addGap(9, 9, 9)
                .addComponent(lblNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPlantel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDuracion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUniversidad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSemestres)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Anterior)
                    .addComponent(Siguiente)
                    .addComponent(Ultimo)
                    .addComponent(Principio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Regresar)
                    .addComponent(Modificar))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PrincipioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrincipioActionPerformed
        indiceActual = 0;
        mostrarDatos(indiceActual);
    }//GEN-LAST:event_PrincipioActionPerformed

    private void RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarActionPerformed
        this.dispose();

        Menus.MenuCarrera menuPrincipal = new Menus.MenuCarrera();
        menuPrincipal.setVisible(true);
    }//GEN-LAST:event_RegresarActionPerformed

    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed
        this.dispose();

        ModificarCarrera modificar = new ModificarCarrera();
        modificar.setVisible(true);
    }//GEN-LAST:event_ModificarActionPerformed

    private void SiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SiguienteActionPerformed
        mostrarDatos(++indiceActual);
    }//GEN-LAST:event_SiguienteActionPerformed

    private void AnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnteriorActionPerformed
        mostrarDatos(--indiceActual);
    }//GEN-LAST:event_AnteriorActionPerformed

    private void UltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UltimoActionPerformed
        indiceActual = carr.size() - 1;
        mostrarDatos(indiceActual);
    }//GEN-LAST:event_UltimoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Anterior;
    private javax.swing.JButton Modificar;
    private javax.swing.JButton Principio;
    private javax.swing.JButton Regresar;
    private javax.swing.JButton Siguiente;
    private javax.swing.JButton Ultimo;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblDuracion;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPlantel;
    private javax.swing.JLabel lblSemestres;
    private javax.swing.JLabel lblUniversidad;
    // End of variables declaration//GEN-END:variables

    private void mostrarDatos(int index) {
        if (index >= 0 && index < carr.size()) {
            Clases.Carrera carrera = carr.get(index);
            lblId.setText("Matricula: " + carrera.getId());
            lblNombre.setText("Nombre: " + carrera.getNombre());
            lblPlantel.setText("Apellidos: " + carrera.getPlantel());
            lblDuracion.setText("Edad: " + carrera.getDuracion());
            lblUniversidad.setText("Carrera: " + carrera.getUniversidad());
            lblSemestres.setText("Semestre: " + carrera.getSemestres());
        }
    }

}
