/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CRUDG;

/**
 *
 * @author hecto
 */
public class BajasGrupo extends javax.swing.JFrame {

    private java.util.ArrayList<Clases.Grupo> grup;

    private int indiceActual = 0;

    /**
     * Creates new form BajasGrupo
     */
    public BajasGrupo() {
        initComponents();

        try {
            java.io.FileInputStream fis = new java.io.FileInputStream("Grupos");
            java.io.ObjectInputStream ois = new java.io.ObjectInputStream(fis);
            grup = (java.util.ArrayList<Clases.Grupo>) ois.readObject();
            ois.close();
            mostrarDatos(indiceActual);
        } catch (java.io.IOException | ClassNotFoundException es) {
            System.out.println("Error al cargar datos desde el archivo: " + es.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblId = new javax.swing.JLabel();
        lblGrupo = new javax.swing.JLabel();
        lblElegir = new javax.swing.JLabel();
        txtElegir = new javax.swing.JTextField();
        Buscar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        Regresar = new javax.swing.JButton();
        Borrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblId.setText("ID:");

        lblGrupo.setText("Grupo:");

        lblElegir.setText("Número de ID:");

        Buscar.setText("Buscar");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel7.setText("BAJAS - GRUPO");

        Regresar.setText("REGRESAR");
        Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarActionPerformed(evt);
            }
        });

        Borrar.setText("Dar de baja");
        Borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblId)
                        .addComponent(lblGrupo))
                    .addComponent(lblElegir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtElegir, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(Buscar)
                .addGap(26, 26, 26))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(Borrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Regresar)
                .addGap(81, 81, 81))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtElegir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblElegir)
                    .addComponent(Buscar))
                .addGap(39, 39, 39)
                .addComponent(lblId)
                .addGap(9, 9, 9)
                .addComponent(lblGrupo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Borrar)
                    .addComponent(Regresar))
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        String idText = txtElegir.getText();
        txtElegir.setText("");

        try {
            int id = Integer.parseInt(idText);
            boolean encontrado = false;
            for (int i = 0; i < grup.size(); i++) {
                if (grup.get(i).getId() == id) {
                    mostrarDatos(i);
                    encontrado = true;
                    break;
                }
            }
            if (!encontrado) {
                javax.swing.JOptionPane.showMessageDialog(this, "ID no encontrada.");
            }
        } catch (NumberFormatException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor ingrese un numero valido en la ID.");
        }
    }//GEN-LAST:event_BuscarActionPerformed

    private void RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarActionPerformed
        this.dispose();

        Menus.MenuGrupo menuPrincipal = new Menus.MenuGrupo();
        menuPrincipal.setVisible(true);
    }//GEN-LAST:event_RegresarActionPerformed

    private void BorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrarActionPerformed
        String idText = txtElegir.getText();

        try {
            int id = Integer.parseInt(idText);
            boolean encontrado = false;
            for (int i = 0; i < grup.size(); i++) {
                if (grup.get(i).getId() == id) {
                    grup.remove(i);
                    encontrado = true;
                    break;
                }
            }
            if (encontrado) {
                javax.swing.JOptionPane.showMessageDialog(this, "Grupo borrado exitosamente.");

                try {
                    java.io.FileOutputStream fos = new java.io.FileOutputStream("Grupos");
                    java.io.ObjectOutputStream oos = new java.io.ObjectOutputStream(fos);
                    oos.writeObject(grup);
                    oos.close();
                } catch (java.io.IOException ex) {
                    System.out.println("Error al guardar datos en el archivo: " + ex.toString());
                }

                lblId.setText("ID");
                lblGrupo.setText("Grupo");
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "ID no encontrada.");
            }
        } catch (NumberFormatException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor ingrese un número válido en la ID.");
        }
    }//GEN-LAST:event_BorrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Borrar;
    private javax.swing.JButton Buscar;
    private javax.swing.JButton Regresar;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblElegir;
    private javax.swing.JLabel lblGrupo;
    private javax.swing.JLabel lblId;
    private javax.swing.JTextField txtElegir;
    // End of variables declaration//GEN-END:variables

    private void mostrarDatos(int index) {
        if (index >= 0 && index < grup.size()) {
            Clases.Grupo grupo = grup.get(index);
            lblId.setText("Matricula: " + grupo.getId());
            lblGrupo.setText("Nombre: " + grupo.getGrupo());
        }
    }

}
