/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CRUDG;

/**
 *
 * @author hecto
 */
public class ModificarGrupo extends javax.swing.JFrame {

    private java.util.ArrayList<Clases.Grupo> grup;

    private int indiceActual = 0;

    /**
     * Creates new form ModificarGrupo
     */
    public ModificarGrupo() {
        initComponents();

        try {
            java.io.FileInputStream fis = new java.io.FileInputStream("Grupos");
            java.io.ObjectInputStream ois = new java.io.ObjectInputStream(fis);
            grup = (java.util.ArrayList<Clases.Grupo>) ois.readObject();
            ois.close();
            mostrarDatos(indiceActual);
        } catch (java.io.IOException | ClassNotFoundException es) {
            System.out.println("Error al cargar datos desde el archivo: " + es.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtGrupo = new javax.swing.JTextField();
        lblId = new javax.swing.JLabel();
        lblElegir = new javax.swing.JLabel();
        lblGrupo = new javax.swing.JLabel();
        txtElegir = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        Buscar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        Modificar = new javax.swing.JButton();
        Regresar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblId.setText("ID:");

        lblElegir.setText("ID a modificar:");

        lblGrupo.setText("Grupo:");

        Buscar.setText("Buscar");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel7.setText("MODIFICAR - GRUPO");

        Modificar.setText("Modificar");
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });

        Regresar1.setText("REGRESAR");
        Regresar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Regresar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(lblElegir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtElegir, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(Buscar)
                .addGap(42, 42, 42))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblId)
                                .addGap(22, 22, 22))
                            .addComponent(lblGrupo))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(txtGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(105, 105, 105))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Modificar)
                        .addGap(82, 82, 82)
                        .addComponent(Regresar1)
                        .addGap(94, 94, 94))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtElegir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblElegir)
                    .addComponent(Buscar))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblId)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGrupo)
                    .addComponent(txtGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Modificar)
                    .addComponent(Regresar1))
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        String idBuscar = txtElegir.getText().trim();

        if (idBuscar.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor ingrese una ID a buscar.");
        } else {
            boolean encontrado = false;
            int indiceGrupo = -1;
            for (int i = 0; i < grup.size(); i++) {
                if (String.valueOf(grup.get(i).getId()).equals(idBuscar)) {
                    encontrado = true;
                    indiceGrupo = i;
                    break;
                }
            }

            if (encontrado) {
                mostrarDatos(indiceGrupo);
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "La ID especificada no existe en la base de datos.");
            }

            txtElegir.setText("");
        }
    }//GEN-LAST:event_BuscarActionPerformed

    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed
        String idModificar = txtId.getText().trim();
        String nuevoGrupo = txtGrupo.getText().trim();

        Clases.Grupo grupoModificar = null;
        for (Clases.Grupo grupo : grup) {
            if (String.valueOf(grupo.getId()).equals(idModificar)) {
                grupoModificar = grupo;
                break;
            }
        }

        if (!nuevoGrupo.isEmpty()) {
            grupoModificar.setGrupo(nuevoGrupo);
        }

        txtId.setText("");
        txtGrupo.setText("");

        try {
            java.io.FileOutputStream fos = new java.io.FileOutputStream("Grupos");
            java.io.ObjectOutputStream oos = new java.io.ObjectOutputStream(fos);
            oos.writeObject(grup);
            oos.close();
            javax.swing.JOptionPane.showMessageDialog(this, "Los datos se han modificado y guardado correctamente.");
        } catch (java.io.IOException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al guardar los datos modificados: " + ex.toString());
        }
    }//GEN-LAST:event_ModificarActionPerformed

    private void Regresar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Regresar1ActionPerformed
        this.dispose();

        Menus.MenuGrupo menuPrincipal = new Menus.MenuGrupo();
        menuPrincipal.setVisible(true);
    }//GEN-LAST:event_Regresar1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buscar;
    private javax.swing.JButton Modificar;
    private javax.swing.JButton Regresar1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblElegir;
    private javax.swing.JLabel lblGrupo;
    private javax.swing.JLabel lblId;
    private javax.swing.JTextField txtElegir;
    private javax.swing.JTextField txtGrupo;
    private javax.swing.JTextField txtId;
    // End of variables declaration//GEN-END:variables

    private void mostrarDatos(int index) {
        if (index >= 0 && index < grup.size()) {
            Clases.Grupo grupo = grup.get(index);
            lblId.setText("Matricula: " + grupo.getId());
            lblGrupo.setText("Grupo: " + grupo.getGrupo());
        }
    }

}
