/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CRUDM;

/**
 *
 * @author hecto
 */
public class BajasMateria extends javax.swing.JFrame {

    private java.util.ArrayList<Clases.Materia> mate;

    private int indiceActual = 0;

    /**
     * Creates new form BajasMateria
     */
    public BajasMateria() {
        initComponents();

        try {
            java.io.FileInputStream fis = new java.io.FileInputStream("Materias");
            java.io.ObjectInputStream ois = new java.io.ObjectInputStream(fis);
            mate = (java.util.ArrayList<Clases.Materia>) ois.readObject();
            ois.close();
            mostrarDatos(indiceActual);
        } catch (java.io.IOException | ClassNotFoundException es) {
            System.out.println("Error al cargar datos desde el archivo: " + es.toString());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        lblElegir = new javax.swing.JLabel();
        txtElegir = new javax.swing.JTextField();
        Buscar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        lblDias = new javax.swing.JLabel();
        lblHoras = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblProfesor = new javax.swing.JLabel();
        lblCreditos = new javax.swing.JLabel();
        Borrar = new javax.swing.JButton();
        Regresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblElegir.setText("Número de matricula:");

        Buscar.setText("Buscar");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel7.setText("BAJAS - GRUPO");

        lblDias.setText("Dias:");

        lblHoras.setText("Horas x Semana: ");

        lblId.setText("ID:");

        lblNombre.setText("Nombre: ");

        lblProfesor.setText("Profesor:");

        lblCreditos.setText("Creditos:");

        Borrar.setText("Dar de baja");
        Borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrarActionPerformed(evt);
            }
        });

        Regresar.setText("REGRESAR");
        Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblElegir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtElegir, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Buscar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Borrar)
                                .addGap(59, 59, 59)
                                .addComponent(Regresar))
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(77, 77, 77)))
                .addGap(9, 9, 9))
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblId)
                    .addComponent(lblNombre)
                    .addComponent(lblProfesor)
                    .addComponent(lblCreditos)
                    .addComponent(lblDias)
                    .addComponent(lblHoras))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtElegir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblElegir)
                    .addComponent(Buscar))
                .addGap(18, 18, 18)
                .addComponent(lblId)
                .addGap(9, 9, 9)
                .addComponent(lblNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblProfesor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCreditos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDias)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblHoras)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Borrar)
                            .addComponent(Regresar))
                        .addGap(14, 14, 14))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        String idText = txtElegir.getText();
        txtElegir.setText("");

        try {
            int id = Integer.parseInt(idText);
            boolean encontrado = false;
            for (int i = 0; i < mate.size(); i++) {
                if (mate.get(i).getId() == id) {
                    mostrarDatos(i);
                    encontrado = true;
                    break;
                }
            }
            if (!encontrado) {
                javax.swing.JOptionPane.showMessageDialog(this, "ID no encontrada.");
            }
        } catch (NumberFormatException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor ingrese un numero valido en la ID.");
        }
    }//GEN-LAST:event_BuscarActionPerformed

    private void BorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrarActionPerformed
        String idText = txtElegir.getText();

        try {
            int id = Integer.parseInt(idText);
            boolean encontrado = false;
            for (int i = 0; i < mate.size(); i++) {
                if (mate.get(i).getId() == id) {
                    mate.remove(i);
                    encontrado = true;
                    break;
                }
            }
            if (encontrado) {
                javax.swing.JOptionPane.showMessageDialog(this, "Materia borrada exitosamente.");

                try {
                    java.io.FileOutputStream fos = new java.io.FileOutputStream("Materias");
                    java.io.ObjectOutputStream oos = new java.io.ObjectOutputStream(fos);
                    oos.writeObject(mate);
                    oos.close();
                } catch (java.io.IOException ex) {
                    System.out.println("Error al guardar datos en el archivo: " + ex.toString());
                }

                lblId.setText("ID");
                lblNombre.setText("Nombre");
                lblProfesor.setText("Profesor");
                lblCreditos.setText("Creditos");
                lblDias.setText("Dias Inpuestos");
                lblHoras.setText("Horas a la Semana");
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "ID no encontrada.");
            }
        } catch (NumberFormatException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor ingrese un número válido en la ID.");
        }
    }//GEN-LAST:event_BorrarActionPerformed

    private void RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarActionPerformed
        this.dispose();

        Menus.MenuMateria menuPrincipal = new Menus.MenuMateria();
        menuPrincipal.setVisible(true);
    }//GEN-LAST:event_RegresarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Borrar;
    private javax.swing.JButton Buscar;
    private javax.swing.JButton Regresar;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JLabel lblCreditos;
    private javax.swing.JLabel lblDias;
    private javax.swing.JLabel lblElegir;
    private javax.swing.JLabel lblHoras;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblProfesor;
    private javax.swing.JTextField txtElegir;
    // End of variables declaration//GEN-END:variables

    private void mostrarDatos(int index) {
        if (index >= 0 && index < mate.size()) {
            Clases.Materia materia = mate.get(index);
            lblId.setText("Matricula: " + materia.getId());
            lblNombre.setText("Nombre: " + materia.getNombre());
            lblProfesor.setText("Apellidos: " + materia.getProfesor());
            lblCreditos.setText("Edad: " + materia.getCreditos());
            lblDias.setText("Carrera: " + materia.getDiasI());
            lblHoras.setText("Semestre: " + materia.getHorasS());
        }
    }

}
