/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CRUDM;

/**
 *
 * @author hecto
 */
public class ReportesMateria extends javax.swing.JFrame {
    private java.util.ArrayList<Clases.Materia> mate;
    
    private int indiceActual = 0;
    
    /**
     * Creates new form ReportesMateria
     */
    public ReportesMateria() {
        initComponents();
        
        try {
            java.io.FileInputStream fis = new java.io.FileInputStream("Materias");
            java.io.ObjectInputStream ois = new java.io.ObjectInputStream(fis);
            mate = (java.util.ArrayList<Clases.Materia>) ois.readObject();
            ois.close();
            mostrarDatos(indiceActual);
        } catch (java.io.IOException | ClassNotFoundException es) {
            System.out.println("Error al cargar datos desde el archivo: " + es.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        Modificar = new javax.swing.JButton();
        Regresar = new javax.swing.JButton();
        Ultimo = new javax.swing.JButton();
        Principio = new javax.swing.JButton();
        Anterior = new javax.swing.JButton();
        Siguiente = new javax.swing.JButton();
        lblId = new javax.swing.JLabel();
        lblHoras = new javax.swing.JLabel();
        lblDias = new javax.swing.JLabel();
        lblCreditos = new javax.swing.JLabel();
        lblProfesor = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel7.setText("REPORTES - MATERIA");

        Modificar.setText("MODIFICAR");
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });

        Regresar.setText("REGRESAR");
        Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarActionPerformed(evt);
            }
        });

        Ultimo.setText("Ultimo");
        Ultimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UltimoActionPerformed(evt);
            }
        });

        Principio.setText("Principio");
        Principio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrincipioActionPerformed(evt);
            }
        });

        Anterior.setText("Anterior");
        Anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnteriorActionPerformed(evt);
            }
        });

        Siguiente.setText("Siguiente");
        Siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SiguienteActionPerformed(evt);
            }
        });

        lblId.setText("ID:");

        lblHoras.setText("Horas x Semana: ");

        lblDias.setText("Dias:");

        lblCreditos.setText("Creditos:");

        lblProfesor.setText("Profesor:");

        lblNombre.setText("Nombre: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(91, 91, 91))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Anterior)
                        .addGap(18, 18, 18)
                        .addComponent(Siguiente)
                        .addGap(18, 18, 18)
                        .addComponent(Ultimo)
                        .addGap(18, 18, 18)
                        .addComponent(Principio))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(Modificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                        .addComponent(Regresar)
                        .addGap(49, 49, 49)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblId)
                    .addComponent(lblNombre)
                    .addComponent(lblProfesor)
                    .addComponent(lblCreditos)
                    .addComponent(lblDias)
                    .addComponent(lblHoras))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(lblId)
                .addGap(9, 9, 9)
                .addComponent(lblNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblProfesor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCreditos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDias)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHoras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Anterior)
                    .addComponent(Siguiente)
                    .addComponent(Ultimo)
                    .addComponent(Principio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Regresar)
                    .addComponent(Modificar))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed
        this.dispose();

        ModificarMateria modificar = new ModificarMateria();
        modificar.setVisible(true);
    }//GEN-LAST:event_ModificarActionPerformed

    private void RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarActionPerformed
        this.dispose();

        Menus.MenuMateria menuPrincipal = new Menus.MenuMateria();
        menuPrincipal.setVisible(true);
    }//GEN-LAST:event_RegresarActionPerformed

    private void UltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UltimoActionPerformed
        indiceActual = mate.size() - 1;
        mostrarDatos(indiceActual);
    }//GEN-LAST:event_UltimoActionPerformed

    private void PrincipioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrincipioActionPerformed
        indiceActual = 0;
        mostrarDatos(indiceActual);
    }//GEN-LAST:event_PrincipioActionPerformed

    private void AnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnteriorActionPerformed
        mostrarDatos(--indiceActual);
    }//GEN-LAST:event_AnteriorActionPerformed

    private void SiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SiguienteActionPerformed
        mostrarDatos(++indiceActual);
    }//GEN-LAST:event_SiguienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Anterior;
    private javax.swing.JButton Modificar;
    private javax.swing.JButton Principio;
    private javax.swing.JButton Regresar;
    private javax.swing.JButton Siguiente;
    private javax.swing.JButton Ultimo;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblCreditos;
    private javax.swing.JLabel lblDias;
    private javax.swing.JLabel lblHoras;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblProfesor;
    // End of variables declaration//GEN-END:variables

    private void mostrarDatos(int index) {
        if (index >= 0 && index < mate.size()) {
            Clases.Materia materia = mate.get(index);
            lblId.setText("Matricula: " + materia.getId());
            lblNombre.setText("Nombre: " + materia.getNombre());
            lblProfesor.setText("Apellidos: " + materia.getProfesor());
            lblCreditos.setText("Edad: " + materia.getCreditos());
            lblDias.setText("Carrera: " + materia.getDiasI());
            lblHoras.setText("Semestre: " + materia.getHorasS());
        }
    }

}
