/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CRUDP;

/**
 *
 * @author hecto
 */
public class BajasProfesor extends javax.swing.JFrame {

    private java.util.ArrayList<Clases.Profesor> prof;

    private int indiceActual = 0;

    /**
     * Creates new form BajasProfesor
     */
    public BajasProfesor() {
        initComponents();

        try {
            java.io.FileInputStream fis = new java.io.FileInputStream("Profesores");
            java.io.ObjectInputStream ois = new java.io.ObjectInputStream(fis);
            prof = (java.util.ArrayList<Clases.Profesor>) ois.readObject();
            ois.close();
            mostrarDatos(indiceActual);
        } catch (java.io.IOException | ClassNotFoundException es) {
            System.out.println("Error al cargar datos desde el archivo: " + es.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        Buscar = new javax.swing.JButton();
        txtElegir = new javax.swing.JTextField();
        lblElegir = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblCarrera = new javax.swing.JLabel();
        lblApellidos = new javax.swing.JLabel();
        lblSemestre = new javax.swing.JLabel();
        lblEdad = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        Borrar = new javax.swing.JButton();
        Regresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel7.setText("BAJAS - PROFESOR");

        Buscar.setText("Buscar");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });

        lblElegir.setText("Número de ID:");

        lblNombre.setText("Nombre: ");

        lblCarrera.setText("Carrera:");

        lblApellidos.setText("Apellidos: ");

        lblSemestre.setText("Semestre:");

        lblEdad.setText("Edad:");

        lblId.setText("ID");

        Borrar.setText("Dar de baja");
        Borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrarActionPerformed(evt);
            }
        });

        Regresar.setText("REGRESAR");
        Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblElegir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtElegir, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Buscar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)))
                .addGap(23, 23, 23))
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblId)
                            .addComponent(lblNombre)
                            .addComponent(lblApellidos)
                            .addComponent(lblEdad)
                            .addComponent(lblCarrera)
                            .addComponent(lblSemestre))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(Borrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Regresar)
                        .addGap(79, 79, 79))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtElegir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblElegir)
                    .addComponent(Buscar))
                .addGap(18, 18, 18)
                .addComponent(lblId)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblApellidos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEdad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCarrera)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSemestre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Borrar)
                    .addComponent(Regresar))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        String idText = txtElegir.getText();
        txtElegir.setText("");

        try {
            int id = Integer.parseInt(idText);
            boolean encontrado = false;
            for (int i = 0; i < prof.size(); i++) {
                if (prof.get(i).getId() == id) {
                    mostrarDatos(i);
                    encontrado = true;
                    break;
                }
            }
            if (!encontrado) {
                javax.swing.JOptionPane.showMessageDialog(this, "ID no encontrada.");
            }
        } catch (NumberFormatException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor ingrese un numero valido en el ID.");
        }
    }//GEN-LAST:event_BuscarActionPerformed

    private void BorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrarActionPerformed
        String idText = txtElegir.getText();

        try {
            int id = Integer.parseInt(idText);
            boolean encontrado = false;
            for (int i = 0; i < prof.size(); i++) {
                if (prof.get(i).getId() == id) {
                    prof.remove(i);
                    encontrado = true;
                    break;
                }
            }
            if (encontrado) {
                javax.swing.JOptionPane.showMessageDialog(this, "Profesor borrado exitosamente.");

                try {
                    java.io.FileOutputStream fos = new java.io.FileOutputStream("Profesores");
                    java.io.ObjectOutputStream oos = new java.io.ObjectOutputStream(fos);
                    oos.writeObject(prof);
                    oos.close();
                } catch (java.io.IOException ex) {
                    System.out.println("Error al guardar datos en el archivo: " + ex.toString());
                }

                lblId.setText("ID");
                lblNombre.setText("Nombre");
                lblApellidos.setText("Apellidos");
                lblEdad.setText("Edad");
                lblCarrera.setText("Carrera");
                lblSemestre.setText("Semestre");
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "ID no encontrada.");
            }
        } catch (NumberFormatException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor ingrese un número válido en el ID.");
        }
    }//GEN-LAST:event_BorrarActionPerformed

    private void RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarActionPerformed
        this.dispose();

        Menus.MenuProfesor menuPrincipal = new Menus.MenuProfesor();
        menuPrincipal.setVisible(true);
    }//GEN-LAST:event_RegresarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Borrar;
    private javax.swing.JButton Buscar;
    private javax.swing.JButton Regresar;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblApellidos;
    private javax.swing.JLabel lblCarrera;
    private javax.swing.JLabel lblEdad;
    private javax.swing.JLabel lblElegir;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblSemestre;
    private javax.swing.JTextField txtElegir;
    // End of variables declaration//GEN-END:variables

    private void mostrarDatos(int index) {
        if (index >= 0 && index < prof.size()) {
            Clases.Profesor profesor = prof.get(index);
            lblId.setText("ID: " + profesor.getId());
            lblNombre.setText("Nombre: " + profesor.getNombre());
            lblApellidos.setText("Apellidos: " + profesor.getApellidos());
            lblEdad.setText("Edad: " + profesor.getEdad());
            lblCarrera.setText("Carrera: " + profesor.getCarrera());
            lblSemestre.setText("Semestre: " + profesor.getSemestre());
        }
    }

}
